version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: project_a_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_a:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_a_laravel
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  webserver:
    image: nginx:stable-alpine
    container_name: project_a_nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8090:80" # Đã fix cổng sang 8090

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_a_react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    command: tail -f /dev/null # Lệnh giữ container chạy ổn định

volumes:
  db_data_a:
